/**
 * TICKET ENGINE (FULL MATCH SCHEDULE INTEGRATED)
 * Reads the static JSON file generated by your GitHub Action.
 */
const TicketEngine = {
    listings: [],
    apiEndpoint: './data/live-listings.json', 
    
    // FULL SCHEDULE MAPPING (Imported from match-logic.js)
    // Maps Match ID -> [Team A, Team B]
    matchSchedule: {
        // GROUP A
        1: ["Mexico", "South Africa"], 2: ["Korea Republic", "Winner Play-off D"],
        25: ["Winner Play-off D", "South Africa"], 28: ["Mexico", "Korea Republic"],
        53: ["Winner Play-off D", "Mexico"], 54: ["South Africa", "Korea Republic"],
        // GROUP B
        3: ["Canada", "Winner Play-off A"], 8: ["Qatar", "Switzerland"],
        26: ["Switzerland", "Winner Play-off A"], 27: ["Canada", "Qatar"],
        51: ["Switzerland", "Canada"], 52: ["Winner Play-off A", "Qatar"],
        // GROUP C
        5: ["Brazil", "Morocco"], 7: ["Haiti", "Scotland"],
        29: ["Scotland", "Morocco"], 30: ["Brazil", "Haiti"],
        49: ["Scotland", "Brazil"], 50: ["Morocco", "Haiti"],
        // GROUP D
        4: ["USA", "Paraguay"], 6: ["Australia", "Winner Play-off C"],
        31: ["Winner Play-off C", "Paraguay"], 32: ["USA", "Australia"],
        59: ["Winner Play-off C", "USA"], 60: ["Paraguay", "Australia"],
        
        // GROUP E (FIXED: Swapped M55/M56 based on official schedule images)
        9: ["Côte d'Ivoire", "Ecuador"], 10: ["Germany", "Curaçao"],
        33: ["Germany", "Côte d'Ivoire"], 34: ["Ecuador", "Curaçao"],
        55: ["Curaçao", "Côte d'Ivoire"], // Fixed: Was Ecuador vs Germany
        56: ["Ecuador", "Germany"],       // Fixed: Was Curaçao vs Côte d'Ivoire
        
        // GROUP F
        11: ["Netherlands", "Japan"], 12: ["Winner Play-off B", "Tunisia"],
        35: ["Netherlands", "Winner Play-off B"], 36: ["Tunisia", "Japan"],
        57: ["Japan", "Winner Play-off B"], 58: ["Tunisia", "Netherlands"],
        
        // GROUP G
        15: ["IR Iran", "New Zealand"], 16: ["Belgium", "Egypt"],
        39: ["Belgium", "IR Iran"], 40: ["New Zealand", "Egypt"],
        63: ["Egypt", "IR Iran"], 64: ["New Zealand", "Belgium"],
        // GROUP H
        13: ["Saudi Arabia", "Uruguay"], 14: ["Spain", "Cabo Verde"],
        37: ["Uruguay", "Cabo Verde"], 38: ["Spain", "Saudi Arabia"],
        65: ["Cabo Verde", "Saudi Arabia"], 66: ["Uruguay", "Spain"],
        // GROUP I
        17: ["France", "Senegal"], 18: ["Winner Play-off 2", "Norway"],
        41: ["France", "Winner Play-off 2"], 42: ["Norway", "Senegal"],
        61: ["Norway", "France"], 62: ["Senegal", "Winner Play-off 2"],
        // GROUP J
        19: ["Argentina", "Algeria"], 20: ["Austria", "Jordan"],
        43: ["Argentina", "Austria"], 44: ["Jordan", "Algeria"],
        69: ["Algeria", "Austria"], 70: ["Jordan", "Argentina"],
        // GROUP K
        23: ["Portugal", "Winner Play-off 1"], 24: ["Uzbekistan", "Colombia"],
        47: ["Portugal", "Uzbekistan"], 48: ["Colombia", "Winner Play-off 1"],
        71: ["Colombia", "Portugal"], 72: ["Winner Play-off 1", "Uzbekistan"],
        // GROUP L
        21: ["Ghana", "Panama"], 22: ["England", "Croatia"],
        45: ["England", "Ghana"], 46: ["Panama", "Croatia"],
        67: ["Panama", "England"], 68: ["Croatia", "Ghana"]
    },

    state: {
        loading: false,
        error: null,
        filter: { match: '', city: '', team: '', round: '', category: '' },
        sort: 'matchNo',
    },

    init: async () => {
        await TicketEngine.fetchListings();
        TicketEngine.populateFilters();
        TicketEngine.render();
        
        document.querySelectorAll('.ticket-filter').forEach(el => {
            const eventType = el.tagName === 'INPUT' ? 'input' : 'change';
            el.addEventListener(eventType, (e) => {
                TicketEngine.state.filter[e.target.dataset.filterType] = e.target.value;
                TicketEngine.render();
            });
        });

        const sortSelect = document.getElementById('ticket-sort-select');
        if(sortSelect) {
            sortSelect.addEventListener('change', (e) => {
                TicketEngine.state.sort = e.target.value;
                TicketEngine.render();
            });
        }
    },

    fetchListings: async () => {
        TicketEngine.state.loading = true;
        TicketEngine.renderLoadingState();

        try {
            const response = await fetch(`${TicketEngine.apiEndpoint}?t=${new Date().getTime()}`);
            if (!response.ok) throw new Error(`Data not found: ${response.status}`);
            
            const rawData = await response.json();
            
            let items = [];
            if (Array.isArray(rawData)) items = rawData;
            else if (Array.isArray(rawData.items)) items = rawData.items;
            else if (Array.isArray(rawData.listings)) items = rawData.listings;
            else if (Array.isArray(rawData.data)) items = rawData.data;
            
            TicketEngine.listings = items
                .filter(item => {
                    const title = (item.title || item.name || "").toLowerCase();
                    const rawTitle = item.title || item.name || "";
                    
                    const isRTT = title.includes("right to ticket");
                    const isClub = title.includes("club") || title.includes("pennant");
                    const is2026Match = /m\d+/i.test(rawTitle); 

                    return isRTT && !isClub && is2026Match; 
                })
                .map(item => {
                    const title = item.title || item.name || "Unknown Match";
                    const matchNoMatch = title.match(/M(\d+)/i);
                    const matchNo = matchNoMatch ? parseInt(matchNoMatch[1]) : 0;
                    
                    // Price handling
                    let rawPrice = item.lowestPrice || item.price || item.minPrice || 0;
                    if (rawPrice > 10000 && !title.includes(".")) rawPrice = rawPrice / 100;

                    const cityMatch = title.match(/M\d+\s+([A-Za-z\s]+)/i);
                    const city = cityMatch ? cityMatch[1].trim() : "TBD";

                    // Round Logic
                    let round = "Group Stage";
                    if (matchNo > 72) round = "Round of 32";
                    if (matchNo > 88) round = "Round of 16";
                    if (matchNo > 96) round = "Quarter-Final";
                    if (matchNo > 100) round = "Semi-Final";
                    if (matchNo === 103) round = "Bronze Final";
                    if (matchNo === 104) round = "Final";

                    // --- TEAM POPULATION (FULL SCHEDULE) ---
                    let teams = [];
                    if (TicketEngine.matchSchedule[matchNo]) {
                        teams = TicketEngine.matchSchedule[matchNo]; // Uses the full list from top of file
                    }

                    return {
                        id: item.id || item.uniqueCode || `listing-${Math.random()}`,
                        matchNo: matchNo,
                        matchLabel: title.replace("Collectible also valid as ", "").replace("Right To Ticket ", "RTT "),
                        date: item.matchDate || "TBD",
                        city: city,
                        stadium: "TBD",
                        country: "TBD",
                        round: round,
                        category: title.includes("Category 1") ? "Cat 1" : (title.includes("Category 2") ? "Cat 2" : (title.includes("Category 3") ? "Cat 3" : "General")),
                        faceValue: 0,
                        volumeUsd: 0,
                        volumeSales: 0,
                        lastSale: 0,
                        lastSaleDate: "N/A",
                        startingPrice: rawPrice,
                        teams: teams, // Now populated for ALL group matches
                        fifaCollectUrl: `https://collect.fifa.com/marketplace?tags=rtt-m${matchNo}&referrer=fifalavida`
                    };
                });

            console.log(`TicketEngine: Loaded ${TicketEngine.listings.length} valid 2026 tickets.`);

        } catch (error) {
            console.warn("TicketEngine: Error loading data", error);
            TicketEngine.state.error = "Sync pending.";
            TicketEngine.generateMockData();
        } finally {
            TicketEngine.state.loading = false;
            TicketEngine.render();
        }
    },

    generateMockData: () => {
        TicketEngine.listings = Array.from({length: 5}, (_, i) => ({
            id: `mock-${i}`,
            matchNo: i + 1,
            matchLabel: "Demo Data (Live Sync Failed)",
            startingPrice: 150,
            city: "Mexico City",
            stadium: "Estadio Azteca",
            country: "Mexico",
            round: "Group Stage",
            category: "Cat 1",
            faceValue: 0,
            volumeUsd: 0,
            volumeSales: 0,
            lastSale: 0,
            lastSaleDate: "-",
            teams: ["Mexico", "South Africa"],
            fifaCollectUrl: "#"
        }));
    },

    renderLoadingState: () => {
        const container = document.getElementById('ticket-table-body');
        if(container) container.innerHTML = `<div class="col-span-full p-12 text-center text-emerald-400 animate-pulse font-mono uppercase">Updating prices...</div>`;
    },

    populateFilters: () => {
        const populateSelect = (id, items) => {
            const sel = document.getElementById(id);
            if(!sel) return;
            const current = sel.value;
            sel.innerHTML = `<option value="">All</option>`;
            items.filter(Boolean).sort().forEach(item => {
                const opt = document.createElement('option');
                opt.value = item;
                opt.innerText = item;
                sel.appendChild(opt);
            });
            sel.value = current;
        };

        const cities = [...new Set(TicketEngine.listings.map(l => l.city))];
        const rounds = [...new Set(TicketEngine.listings.map(l => l.round))];
        const cats = [...new Set(TicketEngine.listings.map(l => l.category))];
        // Flatten the teams array so "Mexico" and "South Africa" become individual filter options
        const teams = [...new Set(TicketEngine.listings.flatMap(l => l.teams || []))];

        populateSelect('filter-city', cities);
        populateSelect('filter-team', teams);
        populateSelect('filter-round', rounds);
        populateSelect('filter-category', cats);
    },

    render: () => {
        const container = document.getElementById('ticket-table-body');
        const countSpan = document.getElementById('ticket-count');
        if (!container) return;

        let result = TicketEngine.listings.filter(row => {
            const f = TicketEngine.state.filter;
            
            if (f.city && row.city !== f.city) return false;
            if (f.category && row.category !== f.category) return false;
            if (f.round && row.round !== f.round) return false;
            
            // Team Filter (Exact match or includes)
            if (f.team && (!row.teams || !row.teams.includes(f.team))) return false;

            // Match Number Filter
            if (f.match) {
                const searchStr = f.match.toLowerCase().replace(/\D/g, ''); 
                const rowMatchStr = String(row.matchNo);
                if (searchStr && !rowMatchStr.includes(searchStr)) return false;
            }

            return true;
        });

        const s = TicketEngine.state.sort;
        result.sort((a, b) => {
            if (s === 'priceAsc') return a.startingPrice - b.startingPrice;
            if (s === 'priceDesc') return b.startingPrice - a.startingPrice;
            return a.matchNo - b.matchNo;
        });

        if (countSpan) countSpan.innerText = `${result.length} Listings`;

        if (result.length === 0) {
            container.innerHTML = `<div class="col-span-full p-8 text-center text-gray-500">No tickets found.</div>`;
            return;
        }

        container.innerHTML = result.map(row => `
            <div class="bg-white/5 border border-white/10 rounded-xl p-4 flex flex-col justify-between hover:border-emerald-500/50 transition-all duration-300 group">
                <div>
                    <div class="flex justify-between items-start mb-3">
                        <div>
                            <div class="font-bold text-white text-base">${row.matchLabel}</div>
                            ${row.teams.length > 0 ? `<div class="text-sm text-emerald-400 mt-1">${row.teams.join(' vs ')}</div>` : ''}
                        </div>
                        <div class="text-emerald-400 font-mono font-bold text-lg">#${row.matchNo}</div>
                    </div>
                    
                    <div class="text-sm space-y-2 text-gray-300 mb-4">
                        <div class="flex items-center gap-2"><i data-lucide="map-pin" class="w-3 h-3 text-gray-500"></i> ${row.city}</div>
                        <div class="flex items-center gap-2"><i data-lucide="trophy" class="w-3 h-3 text-gray-500"></i> ${row.round}</div>
                    </div>
                </div>

                <div class="border-t border-white/10 pt-3 flex justify-between items-center">
                    <span class="bg-white/10 px-2 py-1 rounded text-xs uppercase tracking-widest text-gray-300">${row.category}</span>
                    <a href="${row.fifaCollectUrl}" target="_blank" class="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-500 text-white px-4 py-2 rounded font-bold text-sm uppercase transition">
                        $${row.startingPrice.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}
                        <i data-lucide="external-link" class="w-3 h-3"></i>
                    </a>
                </div>
            </div>
        `).join('');

        if(window.lucide) window.lucide.createIcons();
    }
};