/**
 * TICKET ENGINE (STRICT FILTER)
 * Reads the static JSON file generated by your GitHub Action.
 */
const TicketEngine = {
    listings: [],
    apiEndpoint: './data/live-listings.json', 
    
    state: {
        loading: false,
        error: null,
        filter: { country: '', city: '', team: '', round: '', category: '' },
        sort: 'matchNo',
    },

    init: async () => {
        await TicketEngine.fetchListings();
        TicketEngine.populateFilters();
        TicketEngine.render();
        
        document.querySelectorAll('.ticket-filter').forEach(select => {
            select.addEventListener('change', (e) => {
                TicketEngine.state.filter[e.target.dataset.filterType] = e.target.value;
                TicketEngine.render();
            });
        });

        const sortSelect = document.getElementById('ticket-sort-select');
        if(sortSelect) {
            sortSelect.addEventListener('change', (e) => {
                TicketEngine.state.sort = e.target.value;
                TicketEngine.render();
            });
        }
    },

    fetchListings: async () => {
        TicketEngine.state.loading = true;
        TicketEngine.renderLoadingState();

        try {
            const response = await fetch(`${TicketEngine.apiEndpoint}?t=${new Date().getTime()}`);
            if (!response.ok) throw new Error(`Data not found: ${response.status}`);
            
            const rawData = await response.json();
            
            let items = [];
            if (Array.isArray(rawData)) items = rawData;
            else if (Array.isArray(rawData.items)) items = rawData.items;
            else if (Array.isArray(rawData.listings)) items = rawData.listings;
            else if (Array.isArray(rawData.data)) items = rawData.data;
            
            // STRICT FILTERING LOGIC
            TicketEngine.listings = items
                .filter(item => {
                    const title = (item.title || item.name || "").toLowerCase();
                    
                    // 1. Must contain "Right To Ticket"
                    const isRTT = title.includes("right to ticket");
                    
                    // 2. Must NOT be Club World Cup (removes "Club", "Flamengo", etc)
                    const isClub = title.includes("club") || title.includes("pennant");
                    
                    // 3. Must look like a 2026 Match (M followed by digits)
                    const is2026Match = /m\d+/.test(item.title || "");

                    return isRTT && !isClub && is2026Match; 
                })
                .map(item => {
                    const title = item.title || item.name || "Unknown Match";
                    const matchNo = item.matchNumber || (title.match(/M(\d+)/) ? parseInt(title.match(/M(\d+)/)[1]) : 0);
                    
                    // Price handling (cents to dollars)
                    let rawPrice = item.lowestPrice || item.price || item.minPrice || 0;
                    if (rawPrice > 10000 && !title.includes(".")) rawPrice = rawPrice / 100;

                    return {
                        id: item.id || item.uniqueCode || `listing-${Math.random()}`,
                        matchNo: matchNo,
                        matchLabel: title.replace("Collectible also valid as ", "").replace("Right To Ticket ", "RTT "),
                        date: item.matchDate || "TBD",
                        city: item.city || (title.match(/M\d+\s+([A-Za-z\s]+)/) ? title.match(/M\d+\s+([A-Za-z\s]+)/)[1].trim() : "TBD"),
                        stadium: "TBD",
                        country: "TBD",
                        round: "Group Stage", 
                        category: title.includes("Category 1") ? "Cat 1" : (title.includes("Category 2") ? "Cat 2" : (title.includes("Category 3") ? "Cat 3" : "General")),
                        faceValue: 0,
                        volumeUsd: 0,
                        volumeSales: 0,
                        lastSale: 0,
                        lastSaleDate: "N/A",
                        startingPrice: rawPrice,
                        teams: [],
                        fifaCollectUrl: `https://collect.fifa.com/marketplace?tags=rtt-m${matchNo}&referrer=fifalavida`
                    };
                });

            console.log(`TicketEngine: Loaded ${TicketEngine.listings.length} valid 2026 tickets.`);

        } catch (error) {
            console.warn("TicketEngine: Error loading data", error);
            TicketEngine.state.error = "Sync pending.";
            TicketEngine.generateMockData();
        } finally {
            TicketEngine.state.loading = false;
            TicketEngine.render();
        }
    },

    generateMockData: () => {
        TicketEngine.listings = Array.from({length: 5}, (_, i) => ({
            id: `mock-${i}`,
            matchNo: i + 1,
            matchLabel: "Demo Data (Live Sync Failed)",
            startingPrice: 150,
            city: "Mexico City",
            stadium: "Estadio Azteca",
            country: "Mexico",
            round: "Group Stage",
            category: "Cat 1",
            faceValue: 0,
            volumeUsd: 0,
            volumeSales: 0,
            lastSale: 0,
            lastSaleDate: "-",
            teams: [],
            fifaCollectUrl: "#"
        }));
    },

    renderLoadingState: () => {
        const tbody = document.getElementById('ticket-table-body');
        if(tbody) tbody.innerHTML = `<tr><td colspan="9" class="p-12 text-center text-emerald-400 animate-pulse font-mono uppercase">Updating prices...</td></tr>`;
    },

    populateFilters: () => {
        const populateSelect = (id, items) => {
            const sel = document.getElementById(id);
            if(!sel) return;
            const current = sel.value;
            sel.innerHTML = `<option value="">All</option>`;
            items.filter(Boolean).sort().forEach(item => {
                const opt = document.createElement('option');
                opt.value = item;
                opt.innerText = item;
                sel.appendChild(opt);
            });
            sel.value = current;
        };

        const cities = [...new Set(TicketEngine.listings.map(l => l.city))];
        const countries = [...new Set(TicketEngine.listings.map(l => l.country))];
        const rounds = [...new Set(TicketEngine.listings.map(l => l.round))];
        const cats = [...new Set(TicketEngine.listings.map(l => l.category))];

        populateSelect('filter-country', countries);
        populateSelect('filter-city', cities);
        populateSelect('filter-round', rounds);
        populateSelect('filter-category', cats);
    },

    render: () => {
        const tbody = document.getElementById('ticket-table-body');
        const countSpan = document.getElementById('ticket-count');
        if (!tbody) return;

        let result = TicketEngine.listings.filter(row => {
            const f = TicketEngine.state.filter;
            if (f.city && row.city !== f.city) return false;
            if (f.category && row.category !== f.category) return false;
            return true;
        });

        const s = TicketEngine.state.sort;
        result.sort((a, b) => {
            if (s === 'priceAsc') return a.startingPrice - b.startingPrice;
            if (s === 'priceDesc') return b.startingPrice - a.startingPrice;
            return a.matchNo - b.matchNo;
        });

        if (countSpan) countSpan.innerText = `${result.length} Listings`;

        if (result.length === 0) {
            tbody.innerHTML = `<tr><td colspan="9" class="p-8 text-center text-gray-500">No tickets found.</td></tr>`;
            return;
        }

        tbody.innerHTML = result.map(row => `
            <tr class="border-b border-white/5 hover:bg-white/5 transition group">
                <td class="p-4 text-emerald-400 font-mono font-bold">#${row.matchNo}</td>
                <td class="p-4">
                    <div class="font-bold text-white text-sm">${row.matchLabel}</div>
                </td>
                <td class="p-4 text-gray-300">${row.city}</td>
                <td class="p-4 text-sm text-gray-400">${row.round}</td>
                <td class="p-4"><span class="bg-white/10 px-2 py-1 rounded text-xs uppercase tracking-widest text-gray-300">${row.category}</span></td>
                <td class="p-4">
                    <a href="${row.fifaCollectUrl}" target="_blank" class="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-500 text-white px-4 py-2 rounded font-bold text-sm uppercase transition">
                        $${row.startingPrice.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})} <i data-lucide="external-link" class="w-3 h-3"></i>
                    </a>
                </td>
            </tr>
        `).join('');

        if(window.lucide) window.lucide.createIcons();
    }
};